services:
  postgres:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      volumes:
        - ./scr/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports: 
       - "5432:5432"
  bot:
    depends_on:
      - postgres
    build: .
    env_file: ./.env